# syntax=docker/dockerfile:1

FROM node:latest AS development

ENV CI=true
ENV PORT=3000

WORKDIR /code
COPY package.json /code/package.json
COPY package-lock.json /code/package-lock.json
COPY tailwind.config.js /code/tailwind.config.js
RUN npm ci
COPY . /code

#CMD [ "npm", "ci", "&&", "npm", "dev" ]
CMD [ "npm", "run", "dev" ]

FROM development AS builder
RUN npm build

WORKDIR /code
CMD [ "npm", "ci" ]

FROM development as dev-envs
RUN <<EOF
apt-get update
apt-get install -y --no-install-recommends git
EOF

RUN <<EOF
useradd -s /bin/bash -m vscode
groupadd docker
usermod -aG docker vscode
EOF
# install Docker tools (cli, buildx, compose)
COPY --from=gloursdocker/docker / /
CMD [ "npm", "run", "dev" ]

FROM nginx:alpine

COPY --from=builder /code/dist /usr/share/nginx/html