# syntax=docker/dockerfile:1

FROM node:latest AS development

ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV

WORKDIR /code

# I could add testing ports 9229 and 9230 if I wanted to test or debug.
ARG PORT=8000
ENV PORT $PORT
EXPOSE $PORT 9229 9230

COPY package.json /code/package.json
COPY package-lock.json /code/package-lock.json
# running ci to avoid updating and causing any issue later on.
RUN npm ci

# copy in our source code last, as it changes the most
COPY . /code

CMD ["node", "src/app.js"]

FROM development as dev-envs
RUN <<EOF
apt-get update
apt-get install -y --no-install-recommends git
EOF

RUN <<EOF
useradd -s /bin/bash -m vscode
groupadd docker
usermod -aG docker vscode
EOF
# install Docker tools (cli, buildx, compose)
COPY --from=gloursdocker/docker / /